dataset:
  dataset_name: "Cora"
subgraph:
  num_subgraphs: 7
  delta: 20
  train_ratio: 0.1
  test_ratio: 0.5
model:
  num_samples: [5, 10]
  batch: False
  batch_size: 64
  epochs_local: 1
  lr: 0.002
  weight_decay: 0.0005
  dropout: 0.5
  gnn_layer_type: "sage"
  propagate_type: "GNN"
  epoch_classifier: 20
  metric: "acc"
feature_model:
  gnn_layer_sizes: [128]
  mlp_layer_sizes: [32]
  mp_layers: 3
structure_model:
  GNN_structure_layers_sizes: [128, 64, 32]
  MP_structure_layers_size: [256]
  mp_layers: 7
  # structure_type: "struc2vec"
  # structure_type: "mp"
  # structure_type: "degree"
  # structure_type: "GDV"
  structure_type: "random"
  # structure_type: "node2vec"
  num_structural_features: 256
  estimate: False
  num_mp_vectors: 10
  gnn_epochs: 500
  mlp_epochs: 200
node2vec:
  epochs: 50
  walk_length: 20
  context_size: 10
  walks_per_node: 10
  num_negative_samples: 1
  p: 1
  q: 1
  show_bar: True
fedsage:
  neighgen_epochs: 30
  num_pred: 5
  latent_dim: 128
  hidden_layer_sizes: [32]
  impaired_train_nodes_ratio: 0.6
  impaired_test_nodes_ratio: 0.2
  hidden_portion: 0.5
  use_inter_connections: True
  a: 1
  b: 0
  c: 1

