dataset:
  # dataset_name: "PubMed"
  dataset_name: "Cora"
  # dataset_name: "CiteSeer"
  # dataset_name: "chameleon"
  # dataset_name : "squirrel"
  # dataset_name : "Minesweeper"
  # dataset_name : "Tolokers"
  # dataset_name: "Heterophilic_example"
  # dataset_name: "Homophilic_example"
subgraph:
  num_subgraphs: 7
  delta: 20
model:
  num_samples: [5, 10]
  batch: False
  batch_size: 64
  epochs_local: 1
  lr: 0.001
  weight_decay: 0.0005
  dropout: 0.5
  gen_epochs: 100
  gnn_layer_type: "sage"
  epoch_classifier: 60
  gnn_layer_sizes: [128, 64]
  mlp_layer_sizes: [64]
structure_model:
  sd_ratio: 0
  structure_layers_size: [128, 64]
  # structure_type: "struc2vec"
  # structure_type: "mp"
  # structure_type: "degree"
  # structure_type: "GDV"
  # structure_type: "node2vec"
  structure_type: "random"
  # num_structural_features: 100
  num_structural_features: 256
  # loss: "both"
  # loss: "homophily"
  loss: "heterophily"
  num_mp_vectors: 10
  cosine_similarity_predictor_epochs: 250
  gnn_epochs: 500
  mlp_epochs: 200
