dataset:
  # dataset_name: "PubMed"
  # dataset_name: "Cora"
  # dataset_name: "CiteSeer"
  # dataset_name: "chameleon"
  # dataset_name : "squirrel"
  # dataset_name : "Minesweeper"
  # dataset_name : "Tolokers"
  # dataset_name: "Heterophilic_example"
  dataset_name: "Homophilic_example"
subgraph:
  num_subgraphs: 7
  delta: 20
model:
  num_samples: [5, 10]
  batch_size: 64
  epochs_local: 1
  lr: 0.001
  weight_decay: 1e-4
  dropout: 0.5
  gen_epochs: 100
  epoch_classifier: 150
  classifier_layer_sizes: [128, 64]
structure_model:
  sd_ratio: 1
  structure_layers_size: [128, 64]
  # structure_type: "struc2vec"
  # structure_type: "mp"
  structure_type: "degree"
  # structure_type: "GDV"
  # structure_type: "node2vec"
  # num_structural_features: 100
  num_structural_features: 73
  # loss: "both"
  # loss: "homophily"
  loss: "heterophily"
  num_mp_vectors: 10
